repos:
  # Security: Check for secrets and API keys
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Security: Detect secrets using detect-secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
              .*\.example\..*|
              .*_example\..*|
              \.env\.example|
              config\.example\.toml|
              .*\.md|
              .*\.txt
          )$

  # Security: Ban dangerous patterns
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: text-unicode-replacement-char

  # Custom security checks
  - repo: local
    hooks:
      - id: check-api-keys
        name: Check for API keys in config files
        entry: bash -c 'if grep -r "sk-" config/ --include="*.toml" --include="*.yaml" --include="*.yml" --include="*.json" 2>/dev/null | grep -v example | grep -v "#"; then echo "ERROR: Found potential API keys in config files!"; exit 1; fi'
        language: system
        pass_filenames: false
        
      - id: check-secrets-in-toml
        name: Check for secrets in TOML files
        entry: bash -c 'if grep -r "api_key.*=" config/ --include="*.toml" 2>/dev/null | grep -v "#" | grep -v example; then echo "ERROR: Found uncommented api_key in TOML files!"; exit 1; fi'
        language: system
        pass_filenames: false

  # Code quality
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]